// <auto-generated />
using System;
using ConsoleApp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Site.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190401195937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("ConsoleApp2.Models.AdditionalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("AdditionalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gold",
                            Name = "Ring",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Milota",
                            Name = "Angels",
                            Price = 9999.0
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("CountChildren");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.Property<string>("Job");

                    b.Property<int>("NationalityId");

                    b.Property<string>("Passport");

                    b.Property<string>("Phone");

                    b.Property<float>("Weight");

                    b.Property<float>("Width");

                    b.Property<int>("ZodiacSignId");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.HasIndex("ZodiacSignId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "gomel",
                            Birthday = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CountChildren = 2,
                            FullName = "Tom Anderson",
                            Gender = "man",
                            Job = "Cleaner",
                            NationalityId = 1,
                            Passport = "HB2721659",
                            Phone = "+375298645383",
                            Weight = 100f,
                            Width = 100f,
                            ZodiacSignId = 1
                        },
                        new
                        {
                            Id = 2,
                            Adress = "gomel",
                            Birthday = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CountChildren = 0,
                            FullName = "Vlad Pinchuk",
                            Gender = "man",
                            Job = "Programmer",
                            NationalityId = 1,
                            Passport = "HB27324329",
                            Phone = "+37526702656",
                            Weight = 90f,
                            Width = 190f,
                            ZodiacSignId = 2
                        },
                        new
                        {
                            Id = 3,
                            Adress = "gomel",
                            Birthday = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CountChildren = 20,
                            FullName = "Pavel Stelmah",
                            Gender = "man",
                            Job = "Front end developer",
                            NationalityId = 3,
                            Passport = "HB2722349",
                            Phone = "+375292343483",
                            Weight = 80f,
                            Width = 100f,
                            ZodiacSignId = 3
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.CustomerAdditional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdditionalServiceId");

                    b.Property<int>("CustomerId");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalServiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAdditional");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalServiceId = 1,
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdditionalServiceId = 1,
                            CustomerId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdditionalServiceId = 2,
                            CustomerId = 3
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Remarks");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Belarus",
                            Remarks = "cool people"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Russian",
                            Remarks = "countrymate"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pole",
                            Remarks = "also countrymate"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.ZodiacSign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ZodiacSigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "very stubborn",
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 2,
                            Description = "wet",
                            Name = "Aquarius"
                        },
                        new
                        {
                            Id = 3,
                            Description = "dangerous",
                            Name = "Scorpio"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Customer", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConsoleApp2.Models.ZodiacSign", "ZodiacSign")
                        .WithMany()
                        .HasForeignKey("ZodiacSignId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConsoleApp2.Models.CustomerAdditional", b =>
                {
                    b.HasOne("ConsoleApp2.Models.AdditionalService", "AdditionalService")
                        .WithMany("CustomerAdditional")
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConsoleApp2.Models.Customer", "Customer")
                        .WithMany("CustomerAdditional")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
